services:
  postgres:
    container_name: gendocsv3_postgres
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gendocs-network

  backend:
    container_name: gendocsv3_backend
    image: ${BACKEND_DOCKER_IMAGE}
    restart: always
    env_file:
      - .env.production
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    networks:
      - gendocs-network

  frontend:
    container_name: gendocsv3_frontend
    image: ${FRONTEND_DOCKER_IMAGE}
    restart: always
    ports:
      - 8000:3000
    networks:
      - gendocs-network
  
  bull_redis:
    container_name: gendocsv3_bull_redis
    image: redis:7.4-rc1-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - bull-redis-data:/data
    networks:
      - gendocs-network

volumes:
  postgres-data:
  bull-redis-data:

networks:
  gendocs-network:
    driver: bridge
