FROM node:20.10-alpine3.18

WORKDIR /app

RUN apk add --no-cache tzdata

ENV TZ=America/Bogota

RUN cp /usr/share/zoneinfo/America/Bogota /etc/localtime

COPY package*.json ./

RUN npm ci --omiy=dev

COPY . .

RUN npm run build

EXPOSE 3001

CMD npm run migration:run && npm run start:prod
