# SEND GET BY FILTERS
GET http://localhost:3001/api/councils/filter/f?limit=5&offset=0&state=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEYW5pZWxhIiwiZmlyc3RMYXN0TmFtZSI6Ik1vbnRlbmVncm8iLCJzZWNvbmROYW1lIjoiRGFuaWVsYSIsInNlY29uZExhc3ROYW1lIjoiTW9udGVuZWdybyIsIm91dGxvb2tFbWFpbCI6ImRkbG0ubW9udGVuZWdyb0B1dGEuZWR1LmVjIiwiZ29vZ2xlRW1haWwiOiJnZW5kb2NzdjJAZ21haWwuY29tIiwic3ViIjoxLCJyb2xlIjoiQURNSU4iLCJhY2Nlc3NNb2R1bGVzIjpbMSwyLDMsNCw1LDYsNyw4LDksMTAsMTFdLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzE3OTAzNDEyLCJleHAiOjE3MTg1MDgyMTJ9.5uLM6DGfhp5hWNGN2T5Sek-eqvHxhuew9y7Q-qenwA8

