import { MigrationInterface, QueryRunner } from 'typeorm'
import { StudentEntity } from '../students/entities/student.entity'
import { CareerEntity } from '../careers/entites/careers.entity'
import { GENDER } from '../shared/enums/genders'
import { ProvinceEntity } from '../cities/entities/province.entity'
import { CityEntity } from '../cities/entities/city.entity'

export class LoadStudentForTest1705110761172 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const studentRepository =
      queryRunner.connection.getRepository(StudentEntity)

    const provinceRepository =
      queryRunner.connection.getRepository(ProvinceEntity)

    const cityRepository = queryRunner.connection.getRepository(CityEntity)

    const provinces = [
      { name: 'Azuay' },
      { name: 'Bolívar' },
      { name: 'Cañar' },
      { name: 'Carchi' },
      { name: 'Cotopaxi' },
      { name: 'Chimborazo' },
      { name: 'El Oro' },
      { name: 'Esmeraldas' },
      { name: 'Guayas' },
      { name: 'Imbabura' },
      { name: 'Loja' },
      { name: 'Los Rios' },
      { name: 'Manabi' },
      { name: 'Morona Santiago' },
      { name: 'Napo' },
      { name: 'Pastaza' },
      { name: 'Pichincha' },
      { name: 'Tungurahua' },
      { name: 'Zamora Chinchipe' },
      { name: 'Galápagos' },
      { name: 'Sucumbíos' },
      { name: 'Orellana' },
      { name: 'Santo Domingo de Los Tsáchilas' },
      { name: 'Santa Elena' },
      { name: 'Zonas No Delimitadas' },
    ]

    const cities = [
      { name: 'Cuenca', province: { id: 1 } },
      { name: 'Girón', province: { id: 1 } },
      { name: 'Gualaceo', province: { id: 1 } },
      { name: 'Nabón', province: { id: 1 } },
      { name: 'Paute', province: { id: 1 } },
      { name: 'Pucara', province: { id: 1 } },
      { name: 'San Fernando', province: { id: 1 } },
      { name: 'Santa Isabel', province: { id: 1 } },
      { name: 'Sigsig', province: { id: 1 } },
      { name: 'Oña', province: { id: 1 } },
      { name: 'Chordeleg', province: { id: 1 } },
      { name: 'El Pan', province: { id: 1 } },
      { name: 'Sevilla de Oro', province: { id: 1 } },
      { name: 'Guachapala', province: { id: 1 } },
      { name: 'Camilo Ponce Enríquez', province: { id: 1 } },
      { name: 'Guaranda', province: { id: 2 } },
      { name: 'Chillanes', province: { id: 2 } },
      { name: 'Chimbo', province: { id: 2 } },
      { name: 'Echeandía', province: { id: 2 } },
      { name: 'San Miguel', province: { id: 2 } },
      { name: 'Caluma', province: { id: 2 } },
      { name: 'Las Naves', province: { id: 2 } },
      { name: 'Azogues', province: { id: 3 } },
      { name: 'Biblián', province: { id: 3 } },
      { name: 'Cañar', province: { id: 3 } },
      { name: 'La Troncal', province: { id: 3 } },
      { name: 'El Tambo', province: { id: 3 } },
      { name: 'Déleg', province: { id: 3 } },
      { name: 'Suscal', province: { id: 3 } },
      { name: 'Tulcán', province: { id: 4 } },
      { name: 'Bolívar', province: { id: 4 } },
      { name: 'Espejo', province: { id: 4 } },
      { name: 'Mira', province: { id: 4 } },
      { name: 'Montúfar', province: { id: 4 } },
      { name: 'San Pedro de Huaca', province: { id: 4 } },
      { name: 'Latacunga', province: { id: 5 } },
      { name: 'La Maná', province: { id: 5 } },
      { name: 'Pangua', province: { id: 5 } },
      { name: 'Pujili', province: { id: 5 } },
      { name: 'Salcedo', province: { id: 5 } },
      { name: 'Saquisilí', province: { id: 5 } },
      { name: 'Sigchos', province: { id: 5 } },
      { name: 'Riobamba', province: { id: 6 } },
      { name: 'Alausi', province: { id: 6 } },
      { name: 'Colta', province: { id: 6 } },
      { name: 'Chambo', province: { id: 6 } },
      { name: 'Chunchi', province: { id: 6 } },
      { name: 'Guamote', province: { id: 6 } },
      { name: 'Guano', province: { id: 6 } },
      { name: 'Pallatanga', province: { id: 6 } },
      { name: 'Penipe', province: { id: 6 } },
      { name: 'Cumandá', province: { id: 6 } },
      { name: 'Machala', province: { id: 7 } },
      { name: 'Arenillas', province: { id: 7 } },
      { name: 'Atahualpa', province: { id: 7 } },
      { name: 'Balsas', province: { id: 7 } },
      { name: 'Chilla', province: { id: 7 } },
      { name: 'El Guabo', province: { id: 7 } },
      { name: 'Huaquillas', province: { id: 7 } },
      { name: 'Marcabelí', province: { id: 7 } },
      { name: 'Pasaje', province: { id: 7 } },
      { name: 'Piñas', province: { id: 7 } },
      { name: 'Portovelo', province: { id: 7 } },
      { name: 'Santa Rosa', province: { id: 7 } },
      { name: 'Zaruma', province: { id: 7 } },
      { name: 'Las Lajas', province: { id: 7 } },
      { name: 'Esmeraldas', province: { id: 8 } },
      { name: 'Eloy Alfaro', province: { id: 8 } },
      { name: 'Muisne', province: { id: 8 } },
      { name: 'Quinindé', province: { id: 8 } },
      { name: 'San Lorenzo', province: { id: 8 } },
      { name: 'Atacames', province: { id: 8 } },
      { name: 'Rioverde', province: { id: 8 } },
      { name: 'La Concordia', province: { id: 8 } },
      { name: 'Guayaquil', province: { id: 9 } },
      { name: 'Alfredo Baquerizo Moreno (Juján)', province: { id: 9 } },
      { name: 'Balao', province: { id: 9 } },
      { name: 'Balzar', province: { id: 9 } },
      { name: 'Colimes', province: { id: 9 } },
      { name: 'Daule', province: { id: 9 } },
      { name: 'Durán', province: { id: 9 } },
      { name: 'El Empalme', province: { id: 9 } },
      { name: 'El Triunfo', province: { id: 9 } },
      { name: 'Milagro', province: { id: 9 } },
      { name: 'Naranjal', province: { id: 9 } },
      { name: 'Naranjito', province: { id: 9 } },
      { name: 'Palestina', province: { id: 9 } },
      { name: 'Pedro Carbo', province: { id: 9 } },
      { name: 'Samborondón', province: { id: 9 } },
      { name: 'Santa Lucía', province: { id: 9 } },
      { name: 'Salitre (Urbina Jado)', province: { id: 9 } },
      { name: 'San Jacinto de Yaguachi', province: { id: 9 } },
      { name: 'Playas', province: { id: 9 } },
      { name: 'Simón Bolívar', province: { id: 9 } },
      { name: 'Coronel Marcelino Maridueña', province: { id: 9 } },
      { name: 'Lomas de Sargentillo', province: { id: 9 } },
      { name: 'Nobol', province: { id: 9 } },
      { name: 'General Antonio Elizalde', province: { id: 9 } },
      { name: 'Isidro Ayora', province: { id: 9 } },
      { name: 'Ibarra', province: { id: 10 } },
      { name: 'Antonio Ante', province: { id: 10 } },
      { name: 'Cotacachi', province: { id: 10 } },
      { name: 'Otavalo', province: { id: 10 } },
      { name: 'Pimampiro', province: { id: 10 } },
      { name: 'San Miguel de Urcuquí', province: { id: 10 } },
      { name: 'Loja', province: { id: 11 } },
      { name: 'Calvas', province: { id: 11 } },
      { name: 'Catamayo', province: { id: 11 } },
      { name: 'Celica', province: { id: 11 } },
      { name: 'Chaguarpamba', province: { id: 11 } },
      { name: 'Espíndola', province: { id: 11 } },
      { name: 'Gonzanamá', province: { id: 11 } },
      { name: 'Macará', province: { id: 11 } },
      { name: 'Paltas', province: { id: 11 } },
      { name: 'Puyango', province: { id: 11 } },
      { name: 'Saraguro', province: { id: 11 } },
      { name: 'Sozoranga', province: { id: 11 } },
      { name: 'Zapotillo', province: { id: 11 } },
      { name: 'Pindal', province: { id: 11 } },
      { name: 'Quilanga', province: { id: 11 } },
      { name: 'Olmedo', province: { id: 11 } },
      { name: 'Babahoyo', province: { id: 12 } },
      { name: 'Baba', province: { id: 12 } },
      { name: 'Montalvo', province: { id: 12 } },
      { name: 'Puebloviejo', province: { id: 12 } },
      { name: 'Quevedo', province: { id: 12 } },
      { name: 'Urdaneta', province: { id: 12 } },
      { name: 'Ventanas', province: { id: 12 } },
      { name: 'Vínces', province: { id: 12 } },
      { name: 'Palenque', province: { id: 12 } },
      { name: 'Buena Fé', province: { id: 12 } },
      { name: 'Valencia', province: { id: 12 } },
      { name: 'Mocache', province: { id: 12 } },
      { name: 'Quinsaloma', province: { id: 12 } },
      { name: 'Portoviejo', province: { id: 13 } },
      { name: 'Bolívar', province: { id: 13 } },
      { name: 'Chone', province: { id: 13 } },
      { name: 'El Carmen', province: { id: 13 } },
      { name: 'Flavio Alfaro', province: { id: 13 } },
      { name: 'Jipijapa', province: { id: 13 } },
      { name: 'Junín', province: { id: 13 } },
      { name: 'Manta', province: { id: 13 } },
      { name: 'Montecristi', province: { id: 13 } },
      { name: 'Paján', province: { id: 13 } },
      { name: 'Pichincha', province: { id: 13 } },
      { name: 'Rocafuerte', province: { id: 13 } },
      { name: 'Santa Ana', province: { id: 13 } },
      { name: 'Sucre', province: { id: 13 } },
      { name: 'Tosagua', province: { id: 13 } },
      { name: '24 de Mayo', province: { id: 13 } },
      { name: 'Pedernales', province: { id: 13 } },
      { name: 'Olmedo', province: { id: 13 } },
      { name: 'Puerto López', province: { id: 13 } },
      { name: 'Jama', province: { id: 13 } },
      { name: 'Jaramijó', province: { id: 13 } },
      { name: 'San Vicente', province: { id: 13 } },
      { name: 'Morona', province: { id: 14 } },
      { name: 'Gualaquiza', province: { id: 14 } },
      { name: 'Limón Indanza', province: { id: 14 } },
      { name: 'Palora', province: { id: 14 } },
      { name: 'Santiago', province: { id: 14 } },
      { name: 'Sucúa', province: { id: 14 } },
      { name: 'Huamboya', province: { id: 14 } },
      { name: 'San Juan Bosco', province: { id: 14 } },
      { name: 'Taisha', province: { id: 14 } },
      { name: 'Logroño', province: { id: 14 } },
      { name: 'Pablo Sexto', province: { id: 14 } },
      { name: 'Tiwintza', province: { id: 14 } },
      { name: 'Tena', province: { id: 15 } },
      { name: 'Archidona', province: { id: 15 } },
      { name: 'El Chaco', province: { id: 15 } },
      { name: 'Quijos', province: { id: 15 } },
      { name: 'Carlos Julio Arosemena Tola', province: { id: 15 } },
      { name: 'Pastaza', province: { id: 16 } },
      { name: 'Mera', province: { id: 16 } },
      { name: 'Santa Clara', province: { id: 16 } },
      { name: 'Arajuno', province: { id: 16 } },
      { name: 'Quito', province: { id: 17 } },
      { name: 'Cayambe', province: { id: 17 } },
      { name: 'Mejia', province: { id: 17 } },
      { name: 'Pedro Moncayo', province: { id: 17 } },
      { name: 'Rumiñahui', province: { id: 17 } },
      { name: 'San Miguel de Los Bancos', province: { id: 17 } },
      { name: 'Pedro Vicente Maldonado', province: { id: 17 } },
      { name: 'Puerto Quito', province: { id: 17 } },
      { name: 'Ambato', province: { id: 18 } },
      { name: 'Baños de Agua Santa', province: { id: 18 } },
      { name: 'Cevallos', province: { id: 18 } },
      { name: 'Mocha', province: { id: 18 } },
      { name: 'Patate', province: { id: 18 } },
      { name: 'Quero', province: { id: 18 } },
      { name: 'San Pedro de Pelileo', province: { id: 18 } },
      { name: 'Santiago de Píllaro', province: { id: 18 } },
      { name: 'Tisaleo', province: { id: 18 } },
      { name: 'Zamora', province: { id: 19 } },
      { name: 'Chinchipe', province: { id: 19 } },
      { name: 'Nangaritza', province: { id: 19 } },
      { name: 'Yacuambi', province: { id: 19 } },
      { name: 'Yantzaza (Yanzatza)', province: { id: 19 } },
      { name: 'El Pangui', province: { id: 19 } },
      { name: 'Centinela del Cóndor', province: { id: 19 } },
      { name: 'Palanda', province: { id: 19 } },
      { name: 'Paquisha', province: { id: 19 } },
      { name: 'San Cristóbal', province: { id: 20 } },
      { name: 'Isabela', province: { id: 20 } },
      { name: 'Santa Cruz', province: { id: 20 } },
      { name: 'Lago Agrio', province: { id: 21 } },
      { name: 'Gonzalo Pizarro', province: { id: 21 } },
      { name: 'Putumayo', province: { id: 21 } },
      { name: 'Shushufindi', province: { id: 21 } },
      { name: 'Sucumbíos', province: { id: 21 } },
      { name: 'Cascales', province: { id: 21 } },
      { name: 'Cuyabeno', province: { id: 21 } },
      { name: 'Orellana', province: { id: 22 } },
      { name: 'Aguarico', province: { id: 22 } },
      { name: 'La Joya de Los Sachas', province: { id: 22 } },
      { name: 'Loreto', province: { id: 22 } },
      { name: 'Santo Domingo', province: { id: 23 } },
      { name: 'Santa Elena', province: { id: 24 } },
      { name: 'La Libertad', province: { id: 24 } },
      { name: 'Salinas', province: { id: 24 } },
      { name: 'Las Golondrinas', province: { id: 25 } },
      { name: 'Manga del Cura', province: { id: 25 } },
      { name: 'El Piedrero', province: { id: 25 } },
    ]

    await provinceRepository.save(provinces)

    await cityRepository.save(cities)

    const studentsForTest = [
      {
        firstName: 'Lenin',
        secondName: 'Lenin',
        firstLastName: 'LEnin',
        secondLastName: 'Lenin',
        outlookEmail: 'lenin@uta.edu.ec',
        personalEmail: 'lenin@gmail.com',
        phoneNumber: '0979424062',
        regularPhoneNumber: '784512',
        dni: '1850994625',
        registration: '2001',
        folio: '2004',
        gender: GENDER.MALE,
        birthdate: new Date('1999-12-12'),
        canton: { id: 1 },
        vinculationHours: 280,
        internshipHours: 96,
        approvedCredits: 0,
        isActive: true,
        bachelorDegree: 'Bachiller en Ciencias',
        startStudiesDate: new Date('2021-01-01'),
        career: { id: 1 },
      },
      {
        firstName: 'John',
        secondName: 'Doe',
        firstLastName: 'Doe',
        secondLastName: 'Doe',
        outlookEmail: 'john@uta.edu.ec',
        personalEmail: 'john@gmail.com',
        phoneNumber: '0987654321',
        regularPhoneNumber: '123456',
        dni: '1234567890',
        registration: '2022',
        folio: '2025',
        gender: GENDER.MALE,
        birthdate: new Date('2000-01-01'),
        canton: { id: 2 },
        vinculationHours: 300,
        internshipHours: 120,
        approvedCredits: 0,
        isActive: true,
        bachelorDegree: 'Bachiller en Artes',
        startStudiesDate: new Date('2022-02-01'),
        career: { id: 2 },
      },
      {
        firstName: 'Jane',
        secondName: 'Smith',
        firstLastName: 'Smith',
        secondLastName: 'Smith',
        outlookEmail: 'jane@uta.edu.ec',
        personalEmail: 'jane@gmail.com',
        phoneNumber: '0987654322',
        regularPhoneNumber: '654321',
        dni: '0982654321',
        registration: '2023',
        folio: '2026',
        gender: GENDER.FEMALE,
        birthdate: new Date('2001-02-02'),
        canton: { id: 3 },
        vinculationHours: 320,
        internshipHours: 144,
        approvedCredits: 0,
        isActive: true,
        bachelorDegree: 'Bachiller en Letras',
        startStudiesDate: new Date('2023-03-01'),
        career: { id: 3 },
      },
      {
        firstName: 'David',
        secondName: 'Johnson',
        firstLastName: 'Johnson',
        secondLastName: 'Johnson',
        outlookEmail: 'david@uta.edu.ec',
        personalEmail: 'david@gmail.com',
        phoneNumber: '0987654323',
        regularPhoneNumber: '987654',
        dni: '9876543210',
        registration: '2024',
        folio: '2027',
        gender: GENDER.MALE,
        birthdate: new Date('2002-03-03'),
        canton: { id: 4 },
        vinculationHours: 340,
        internshipHours: 168,
        approvedCredits: 0,
        isActive: true,
        bachelorDegree: 'Bachiller en Ciencias Sociales',
        startStudiesDate: new Date('2024-04-01'),
        career: { id: 4 },
      },
      {
        firstName: 'Emily',
        secondName: 'Brown',
        firstLastName: 'Brown',
        secondLastName: 'Brown',
        outlookEmail: 'emily@uta.edu.ec',
        personalEmail: 'emily@gmail.com',
        phoneNumber: '0987654324',
        regularPhoneNumber: '456789',
        dni: '0123456789',
        registration: '2025',
        folio: '2028',
        gender: GENDER.FEMALE,
        birthdate: new Date('2003-04-04'),
        canton: { id: 5 },
        vinculationHours: 360,
        internshipHours: 192,
        approvedCredits: 0,
        isActive: true,
        bachelorDegree: 'Bachiller en Ciencias Naturales',
        startStudiesDate: new Date('2025-05-01'),
        career: { id: 5 },
      },
      {
        firstName: 'Michael',
        secondName: 'Wilson',
        firstLastName: 'Wilson',
        secondLastName: 'Wilson',
        outlookEmail: 'michael@uta.edu.ec',
        personalEmail: 'michael@gmail.com',
        phoneNumber: '0987654325',
        regularPhoneNumber: '987654',
        dni: '9876543291',
        registration: '2026',
        folio: '2029',
        gender: GENDER.MALE,
        birthdate: new Date('2004-05-05'),
        canton: { id: 6 },
        vinculationHours: 380,
        internshipHours: 216,
        approvedCredits: 0,
        isActive: true,
        bachelorDegree: 'Bachiller en Ciencias Exactas',
        startStudiesDate: new Date('2026-06-01'),
        career: { id: 6 },
      },
    ]

    await studentRepository.save(studentsForTest)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const careerRepository = queryRunner.connection.getRepository(CareerEntity)
    const studentRepository =
      queryRunner.connection.getRepository(StudentEntity)

    const studentForTest = await studentRepository.findOne({
      where: { dni: '1850994625' },
    })

    const careerForTest = await careerRepository.findOne({
      where: { name: 'Ingeniería en Sistemas' },
    })

    await studentRepository.remove(studentForTest)
    await careerRepository.remove(careerForTest)
  }
}
