import { ADJECTIVES } from './adjectives'
import { GENDER } from './genders'

export enum DEGREE_MODULES {
  MODULE_NAME = 'Comunes',
  MODULE_CODE = 'COMM',
  SUBMODULE_NAME = 'Actas de grado',
}

export enum DEGREE_ATTENDANCE_ROLES {
  PRINCIPAL = 'M_PRINCIPAL',
  SUBSTITUTE = 'M_SUPLENTE',
  PRESIDENT = 'PRESIDENTE',
  MENTOR = 'TUTOR',
}

export const ATTENDANCE_M_LIMIT = 2

export const GENDER_DESIGNATION = [
  { [GENDER.MALE]: 'el señor', [GENDER.FEMALE]: 'la señorita' },
  {
    [GENDER.MALE]: 'portador',
    [GENDER.FEMALE]: 'portadora',
  },
  {
    [GENDER.MALE]: 'El mencionado señor',
    [GENDER.FEMALE]: 'La mencionada señorita',
  },

  {
    [GENDER.MALE]: 'El mencionado',
    [GENDER.FEMALE]: 'La mencionada',
  },
  { [GENDER.MALE]: 'El señor', [GENDER.FEMALE]: 'La señorita' },
]

export const GENDER_DESIGNATION_VARIABLE = (index: number) =>
  `{{DISNACION_GENERO_${index}}}`

export const MEMBERS_DESIGNATION = {
  [DEGREE_ATTENDANCE_ROLES.PRINCIPAL]: {
    [ADJECTIVES.PLURAL]: 'designados mediante',
    [ADJECTIVES.SINGULAR]: 'designado mediante',
  },
  [DEGREE_ATTENDANCE_ROLES.SUBSTITUTE]: {
    [ADJECTIVES.PLURAL]: 'principalizados con',
    [ADJECTIVES.SINGULAR]: 'principalizado con',
  },
}

export enum STUDENT_DEGREE_CERTIFICATE {
  CREDITS_TEXT = '{{CREDITOS_TEXTO}}',
  CREDITS_NUMBER = '{{CREDITOS_NUMEROS}}',
  INTERNSHIP_HOURS = '{{HORAS_PRACTICAS_NUMEROS}}',
  VINCULATION_HOURS = '{{HORAS_VINCULACION_NUMEROS}}',
  VINCULATION_HOURS_TEXT = '{{HORAS_VINCULACION_TEXTO}}',
  INTERNSHIP_HOURS_TEXT = '{{HORAS_PRACTICAS_TEXTO}}',
  DEGREE_CERTIFICATE_STATUS = '{{ACTAGRADO_ESTADO_UPPER}}',
}

export enum DEGREE_CERTIFICATE_VARIABLES {
  DEGREE_CERTIFICATE_PRESIDENT = '{{ACTAGRADO_PRESIDENTE}}',
  DEGREE_CERTIFICATE_PRESIDENT_DOC_ASSIGNED = '{{ACTAGRADO_PRESIDENTE_DOCU_ASIGNACION}}',
  MEMBERS_DEGREE_CERTIFICATE = '{{ACTAGRADO_MIEMBROS}}',
  FIRST_MEMBER_DEGREE_CERTIFICATE = '{{ACTAGRADO_MIEMBRO1}}',
  SECOND_MEMBER_DEGREE_CERTIFICATE = '{{ACTAGRADO_MIEMBRO2}}',
  CREATED_BY = '{{CREADOPOR}}',
  DECANA = '{{DECANA}}',
  IC_UNIT_PRESIDENT = '{{PRESIDENTE_UNIDAD_IC}}',
  DEGREE_CERTIFICATE_TYPE = '{{ACTAGRADO_TIPO}}',
  DEGREE_CERTIFICATE_TOPIC = '{{ACTAGRADO_TEMA}}',
  FIRST_MEMBER_WITHOUTH_DEGREES = '{{AG_MIEMBRO1_SIN_TITULOS}}',
  SECOND_MEMBER_WITHOUTH_DEGREES = '{{AG_MIEMBRO2_SIN_TITULOS}}',
  FIRST_MEMBER_THIRDL_DEGREE_ABR = '{{AG_MIEMBRO1_TITULO3N_ABR}}',
  SECOND_MEMBER_THIRDL_DEGREE_ABR = '{{AG_MIEMBRO2_TITULO3N_ABR}}',
  FIRST_MEMBER_FOURTHL_DEGREE = '{{AG_MIEMBRO1_TITULO4N_ABR}}',
  SECOND_MEMBER_FOURTHL_DEGREE = '{{AG_MIEMBRO2_TITULO4N_ABR}}',
  FIRST_MEMBER_FOURTHL_DEGREE_START = '{{AG_MIEMBRO1_TITULO4N_START}}',
  SECOND_MEMBER_FOURTHL_DEGREE_START = '{{AG_MIEMBRO2_TITULO4N_START}}',
}

export enum DEGREE_CERTIFICATE_GRADES {
  DEFAULT_SHEET = 'Sheet1!',
  DEFAULT_SHEET_NAME = 'Sheet1',
  DEFAULT_RANGE_ID = 0,
}

export enum CERT_STATUS_ENUM {
  MALE_APRO = 'APROBADO',
  FEMALE_APRO = 'APROBADA',
  MALE_REPRO = 'REPROBADO',
  FEMALE_REPRO = 'REPROBADA',
  NO_PRESENTED = 'NO PRESENTACION',
}

export enum CERT_STATUS_CODE {
  APRO = 'APRO',
  REPR = 'REPR',
  NO_PRESENTED = 'NO_RESENTACION',
}

export const getSTATUS_CODE_BY_CERT_STATUS = (
  status: CERT_STATUS_ENUM | string | undefined,
): CERT_STATUS_CODE => {
  if (status?.includes(CERT_STATUS_CODE.APRO)) {
    return CERT_STATUS_CODE.APRO
  } else if (status?.includes(CERT_STATUS_CODE.REPR)) {
    return CERT_STATUS_CODE.REPR
  } else {
    return CERT_STATUS_CODE.APRO
  }
}

export const ARROGANT_PROFESSORS = {
  'John Paul Reyes Vasquez': 'PhD. John Paul Reyeas Vasquez',
}
