name: Continuous deployment for Gendocs backend

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare environment files
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          ENV_FILE_CREDENTIALS: ${{ secrets.ENV_FILE_CREDENTIALS }}
        run: |
          mkdir -p ./gcp
          echo "$GCP_CREDENTIALS" > ./gcp/credentials.json
          echo "$ENV_FILE_CREDENTIALS" > ./.env

      - name: Tag and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            leninner/gendocsv3:latest
            leninner/gendocsv3:${{ github.ref_name }}
